disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - Carthage
  - Pods

